/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-112515-gba6a5e7a3d-20231026"
#endif /* AVUTIL_FFVERSION_H */
